import { makeDecoder } from '~/common/decode'

const OPPGAVE_KODE = {
  ADR_BANK_OKO: 'Adresse + kontoinformasjon',
  ANALYSE_OKO: 'Analyse',
  ANNET_BAR: 'Annet',
  ANNET_BIL: 'Annet',
  ANNET_ENF: 'Annet',
  ANNET_FOR: 'Annet',
  ANNET_FOS: 'Annet',
  ANNET_GRA: 'Annet',
  ANNET_GRU: 'Annet',
  ANNET_HJE: 'Annet',
  ANNET_KON: 'Annet',
  ANNET_OMS: 'Annet',
  ANNET_SUP: 'Annet',
  ANNET_YRK: 'Annet',
  AR_BII: '2 - Arkiv',
  ATT: 'Attestering',
  AUT: 'Automatisk kontroll',
  AVST_STO: 'Avstemming',
  BE_BAR: 'Behandle henvendelse',
  BE_BIL: 'Behandle henvendelse',
  BE_ENF: 'Behandle henvendelse',
  BE_FOR: 'Behandle henvendelse',
  BE_FOS: 'Behandle henvendelse',
  BE_GRA: 'Behandle henvendelse',
  BE_GRU: 'Behandle henvendelse',
  BEH_HENV_AAP: 'Behandle henvendelse',
  BEH_HENV_ARE: 'Behandle henvendelse',
  BEH_HENV_DAG: 'Behandle henvendelse',
  BEH_HENV_FEI: 'Behandle henvendelse',
  BEH_HENV_IND: 'Behandle henvendelse',
  BEH_HENV_MOB: 'Behandle henvendelse',
  BEH_HENV_OPP: 'Behandle henvendelse',
  BEH_HENV_REH: 'Behandle henvendelse',
  BEH_HENV_SYK: 'Behandle henvendelse',
  BEH_HENV_UFO: 'Behandle henvendelse',
  BEH_HENV_VEN: 'Behandle henvendelse',
  BEH_HENV_YRA: 'Behandle henvendelse',
  BEH_INNT_ENDR: 'Behandle inntektsendring',
  BEH_INNT_OPP: 'Behandle inntektsoppdatering',
  BE_HJE: 'Behandle henvendelse',
  BEH_SAK_BAR: 'Behandle sak',
  BEH_SAK_BIL: 'Behandle sak',
  BEH_SAK_ENF: 'Behandle sak',
  BEH_SAK_ERS: 'Behandle sak',
  BEH_SAK_FOR: 'Behandle sak',
  BEH_SAK_FOS: 'Behandle sak',
  BEH_SAK_GRA: 'Behandle sak',
  BEH_SAK_GRU: 'Behandle sak',
  BEH_SAK_HJE: 'Behandle sak',
  BEH_SAK_KON: 'Behandle sak',
  BEH_SAK_MK_AAR: 'Behandle sak (Manuell)',
  BEH_SAK_MK: 'Behandle sak manuell',
  BEH_SAK_MK_MED: 'Behandle sak (Manuell)',
  BEH_SAK_MK_OMS: 'Behandle sak (Manuell)',
  BEH_SAK_MK_REH: 'Behandle sak (Manuell)',
  BEH_SAK_MK_SAK: 'Behandle sak (Manuell)',
  BEH_SAK_MK_SUP: 'Behandle sak (Manuell)',
  BEH_SAK_MK_SYK: 'Behandle sak (Manuell)',
  BEH_SAK_MK_TRY: 'Behandle sak (Manuell)',
  BEH_SAK_MK_UFO: 'Behandle sak (Manuell)',
  BEH_SAK_MK_YRK: 'Behandle sak (Manuell)',
  BEH_SAK_OMS: 'Behandle sak',
  BEH_SAK_REH: 'Behandle sak',
  BEH_SAK_SAK: 'Behandle sak',
  BEH_SAK_SUP: 'Behandle sak',
  BEH_SAK_SYK: 'Behandle sak',
  BEH_SAK_UFO: 'Behandle sak',
  BEH_SAK_YRK: 'Behandle sak',
  BEH_SED_AAP: 'Behandle SED',
  BEH_SED_BAR: 'Behandle SED',
  BEH_SED_DAG: 'Behandle SED',
  BEH_SED_FOR: 'Behandle SED',
  BEH_SED_GEN: 'Behandle SED',
  BEH_SED_GRA: 'Behandle SED',
  BEH_SED_GRU: 'Behandle SED',
  BEH_SED_KON: 'Behandle SED',
  BEH_SED_MED: 'Behandle SED',
  BEH_SED_OMS: 'Behandle SED',
  BEH_SED_PEN: 'Behandle SED',
  BEH_SED_SAK: 'Behandle SED',
  BEH_SED_SUP: 'Behandle SED',
  BEH_SED_SYK: 'Behandle SED',
  BEH_SED_TRY: 'Behandle SED',
  BEH_SED_UFO: 'Behandle SED',
  BEH_SED_YRK: 'Behandle SED',
  BEH_UND_VED_BAR: 'Behandle underkjent vedtak',
  BEH_UND_VED_GRA: 'Behandle underkjent vedtak',
  BEH_UND_VED_KON: 'Behandle underkjent vedtak',
  BE_KON: 'Behandle henvendelse',
  BE_OMS: 'Behandle henvendelse',
  BEST_ORGINAL_GEN: 'Bestill orginal',
  BEST_RESCAN_GEN: 'Bestill reskanning',
  BE_SUP: 'Behandle henvendelse',
  BE_YRK: 'Behandle henvendelse',
  BR_HENV_PEN: 'Brukerhenvendelse',
  DK_APEN: 'Ny G - Mulig avvik - Har ST',
  DK_LMVT: 'Ny G - Mulig avvik - Har ikke ST',
  DK_LUVT: 'Ny G - Krig og gammel yrkesskade',
  DK_OVR: '4 - Div. kundesenter',
  ENDRING_TRK: 'Endring',
  FAGF_TREKK_OKO: 'Fagforeningstrekk',
  FDR_AAP: 'Fordeling',
  FDR_AAR: 'Fordeling',
  FDR_AGR: 'Fordeling',
  FDR_BAR: 'Fordeling',
  FDR_BIL: 'Fordeling',
  FDR_DAG: 'Fordeling',
  FDR_ENF: 'Fordeling',
  FDR_ERS: 'Fordeling',
  FDR_FEI: 'Fordeling',
  FDR_FOR: 'Fordeling',
  FDR_FOS: 'Fordeling',
  FDR_FUL: 'Fordeling',
  FDR_GEN: 'Fordeling',
  FDR_GRU: 'Fordeling',
  FDR_HEL: 'Fordeling',
  FDR_HJE: 'Fordeling',
  FDR_IAR: 'Fordeling',
  FDR_IND: 'Fordeling',
  FDR_KLA: 'Fordeling',
  FDR_KON: 'Fordeling',
  FDR_KTR: 'Fordeling',
  FDR_MED: 'Fordeling',
  FDR_MOB: 'Fordeling',
  FDR_OMS: 'Fordeling',
  FDR_OPA: 'Fordeling',
  FDR_OPP: 'Fordeling',
  FDR_PER: 'Fordeling',
  FDR_REH: 'Fordeling',
  FDR_REK: 'Fordeling',
  FDR_SAA: 'Fordeling',
  FDR_SAK: 'Fordeling',
  FDR_SAP: 'Fordeling',
  FDR_SER: 'Fordeling',
  FDR_STO: 'Fordeling',
  FDR_SUP: 'Fordeling',
  FDR_SYK: 'Fordeling',
  FDR_SYM: 'Fordeling',
  FDR_TIL: 'Fordeling',
  FDR_TRK: 'Fordeling',
  FDR_TRY: 'Fordeling',
  FDR_UFO: 'Fordeling',
  FDR_UKJ: 'Fordeling',
  FDR_VEN: 'Fordeling',
  FDR_YRA: 'Fordeling',
  FDR_YRK: 'Fordeling',
  FEDREKVOTE_FOR: 'Fedrekvote',
  FEILUTBET_STO: 'Feilutbetalingsvedtak',
  FLY_BAR: 'Flyttesak',
  FLY_BIL: 'Flyttesak',
  FLY_ENF: 'Flyttesak',
  FLY_ERS: 'Flyttesak',
  FLY_FOR: 'Flyttesak',
  FLY_FOS: 'Flyttesak',
  FLY_GRA: 'Flyttesak',
  FLY_GRU: 'Flyttesak',
  FLY_HEL: 'Flyttesak',
  FLY_HJE: 'Flyttesak',
  FLY_KON: 'Flyttesak',
  FLY_MED: 'Flyttesak',
  FLY_OMS: 'Flyttesak',
  FLY_SAK: 'Flyttesak',
  FLY_SUP: 'Flyttesak',
  FLY_SYK: 'Flyttesak',
  FLY_TRY: 'Flyttesak',
  FLY_YRK: 'Flyttesak',
  FORESPSKATT_STO: 'Forespørsel skatt feilutbet.',
  FORESPTIL_STO: 'Forespørsel tiltak',
  FORVALT_KONTO_OKO: 'Forvaltningskonto',
  FORVALT_TREKK_OKO: 'Forvaltningstrekk',
  FRIV_SKATTETREKK_OKO: 'Frivillig skattetrekk',
  GE_BID: '1 - Generell',
  GEN_AAR: 'Generell',
  GEN_AGR: 'Generell',
  GEN_BAR: 'Generell',
  GEN_BIL: 'Generell',
  GEN_ENF: 'Generell',
  GEN_ERS: 'Generell',
  GEN_FOR: 'Generell',
  GEN_FOS: 'Generell',
  GEN_FUL: 'Generell',
  GEN: 'Generell',
  GEN_GRA: 'Generell',
  GEN_GRU: 'Generell',
  GEN_HEL: 'Generell',
  GEN_HJE: 'Generell',
  GEN_KON: 'Generell',
  GEN_KTR: 'Generell',
  GEN_MED: 'Generell',
  GEN_OMS: 'Generell',
  GEN_SAK: 'Generell',
  GEN_SER: 'Generell',
  GEN_STO: 'Generell',
  GEN_SUP: 'Generell',
  GEN_TRK: 'Generell',
  GEN_TRY: 'Generell',
  GEN_YRK: 'Generell',
  GI_VEI_INFO_BAR: 'Gi veiledning og informasjon',
  GI_VEI_INFO_BIL: 'Gi veiledning og informasjon',
  GI_VEI_INFO_ENF: 'Gi veiledning og informasjon',
  GI_VEI_INFO_ERS: 'Gi veiledning og informasjon',
  GI_VEI_INFO_FOR: 'Gi veiledning og informasjon',
  GI_VEI_INFO_FOS: 'Gi veiledning og informasjon',
  GI_VEI_INFO_GRA: 'Gi veiledning og informasjon',
  GI_VEI_INFO_GRU: 'Gi veiledning og informasjon',
  GI_VEI_INFO_HEL: 'Gi veiledning og informasjon',
  GI_VEI_INFO_HJE: 'Gi veiledning og informasjon',
  GI_VEI_INFO_KON: 'Gi veiledning og informasjon',
  GI_VEI_INFO_MED: 'Gi veiledning og informasjon',
  GI_VEI_INFO_OMS: 'Gi veiledning og informasjon',
  GI_VEI_INFO_SAK: 'Gi veiledning og informasjon',
  GI_VEI_INFO_SUP: 'Gi veiledning og informasjon',
  GI_VEI_INFO_TRY: 'Gi veiledning og informasjon',
  GI_VEI_INFO_YRK: 'Gi veiledning og informasjon',
  GOD_VED_BAR: 'Godkjenne vedtak',
  GOD_VED_GRA: 'Godkjenne vedtak',
  GOD_VED_KON: 'Godkjenne vedtak',
  HAST_ADR_OPPLYS_OKO: 'Haster adresseopplysninger',
  HAST_BANK_OPPLYS_OKO: 'Haster bankopplysninger',
  HUSL_TREKK_OKO: 'Husleietrekk',
  IN_BII: '2 - Innkreving',
  INNH_DOK_BAR: 'Innhent dokumentasjon',
  INNH_DOK_BIL: 'Innhent dokumentasjon',
  INNH_DOK_ENF: 'Innhent dokumentasjon',
  INNH_DOK_ERS: 'Innhent dokumentasjon',
  INNH_DOK_FOR: 'Innhent dokumentasjon',
  INNH_DOK_FOS: 'Innhent dokumentasjon',
  INNH_DOK_FUL: 'Innhent dokumentasjon',
  INNH_DOK_GRA: 'Innhent dokumentasjon',
  INNH_DOK_GRU: 'Innhent dokumentasjon',
  INNH_DOK_HEL: 'Innhent dokumentasjon',
  INNH_DOK_HJE: 'Innhent dokumentasjon',
  INNH_DOK_KON: 'Innhent dokumentasjon',
  INNH_DOK_MED: 'Innhent dokumentasjon',
  INNH_DOK_OMS: 'Innhent dokumentasjon',
  INNH_DOK_SAK: 'Innhent dokumentasjon',
  INNH_DOK_SUP: 'Innhent dokumentasjon',
  INNH_DOK_TRY: 'Innhent dokumentasjon',
  INNH_DOK_YRK: 'Innhent dokumentasjon',
  INTERN_STO: 'Intern oppfølging NRM',
  IVE: 'Iverksettelse',
  JF_BID: '1 - Journalføring',
  JFR_AAP: 'Journalføring',
  JFR_AAR: 'Journalføring',
  JFR_AGR: 'Journalføring',
  JFR_BAR: 'Journalføring',
  JFR_BIL: 'Journalføring',
  JFR_DAG: 'Journalføring',
  JFR_ENF: 'Journalføring',
  JFR_ERS: 'Journalføring',
  JFR_FEI: 'Journalføring',
  JFR_FOR: 'Journalføring',
  JFR_FOS: 'Journalføring',
  JFR_FUL: 'Journalføring',
  JFR_GEN: 'Journalføring',
  JFR_GRA: 'Journalføring',
  JFR_GRU: 'Journalføring',
  JFR_HEL: 'Journalføring',
  JFR_HJE: 'Journalføring',
  JFR_IAR: 'Journalføring',
  JFR_IND: 'Journalføring',
  JFR: 'Journalføring',
  JFR_KON: 'Journalføring',
  JFR_KTR: 'Journalføring',
  JFR_MED: 'Journalføring',
  JFR_MOB: 'Journalføring',
  JFR_OKO: 'Journalføring',
  JFR_OMS: 'Journalføring',
  JFR_OPA: 'Journalføring',
  JFR_OPP: 'Journalføring',
  JFR_PER: 'Journalføring',
  JFR_REH: 'Journalføring',
  JFR_REK: 'Journalføring',
  JFR_SAA: 'Journalføring',
  JFR_SAK: 'Journalføring',
  JFR_SAP: 'Journalføring',
  JFR_SER: 'Journalføring',
  JFR_STO: 'Journalføring',
  JFR_SUP: 'Journalføring',
  JFR_SYK: 'Journalføring',
  JFR_SYM: 'Journalføring',
  JFR_TIL: 'Journalføring',
  JFR_TRK: 'Journalføring',
  JFR_TRY: 'Journalføring',
  JFR_UFO: 'Journalføring',
  JFR_VEN: 'Journalføring',
  JFR_YRA: 'Journalføring',
  JFR_YRK: 'Journalføring',
  KONT_BRUK_AAP: 'Kontakt bruker',
  KONT_BRUK_BAR: 'Kontakt bruker',
  KONT_BRUK_BID: 'Kontakt bruker',
  KONT_BRUK_BII: 'Kontakt bruker',
  KONT_BRUK_BIL: 'Kontakt bruker',
  KONT_BRUK_DAG: 'Kontakt bruker',
  KONT_BRUK_ENF: 'Kontakt bruker',
  KONT_BRUK_ERS: 'Kontakt bruker',
  KONT_BRUK_FEI: 'Kontakt bruker',
  KONT_BRUK_FOR: 'Kontakt bruker',
  KONT_BRUK_FOS: 'Kontakt bruker',
  KONT_BRUK_FUL: 'Kontakt bruker',
  KONT_BRUK_GEN: 'Kontakt bruker',
  KONT_BRUK_GRA: 'Kontakt bruker',
  KONT_BRUK_GRU: 'Kontakt bruker',
  KONT_BRUK_HEL: 'Kontakt bruker',
  KONT_BRUK_HJE: 'Kontakt bruker',
  KONT_BRUK_IAR: 'Kontakt bruker',
  KONT_BRUK_IND: 'Kontakt bruker',
  KONT_BRUK_KOM: 'Kontakt bruker',
  KONT_BRUK_KON: 'Kontakt bruker',
  KONT_BRUK_MED: 'Kontakt bruker',
  KONT_BRUK_MOB: 'Kontakt bruker',
  KONT_BRUK_MOT: 'Kontakt bruker',
  KONT_BRUK_OKO: 'Kontakt bruker',
  KONT_BRUK_OMS: 'Kontakt bruker',
  KONT_BRUK_OPA: 'Kontakt bruker',
  KONT_BRUK_OPP: 'Kontakt bruker',
  KONT_BRUK_OVR: 'Kontakt bruker',
  KONT_BRUK_PEN: 'Kontakt bruker',
  KONT_BRUK_PER: 'Kontakt bruker',
  KONT_BRUK_REH: 'Kontakt bruker',
  KONT_BRUK_REK: 'Kontakt bruker',
  KONT_BRUK_SAA: 'Kontakt bruker',
  KONT_BRUK_SAK: 'Kontakt bruker',
  KONT_BRUK_SAP: 'Kontakt bruker',
  KONT_BRUK_SER: 'Kontakt bruker',
  KONT_BRUK_STO: 'Kontakt bruker',
  KONT_BRUK_SUP: 'Kontakt bruker',
  KONT_BRUK_SYK: 'Kontakt bruker',
  KONT_BRUK_TIL: 'Kontakt bruker',
  KONT_BRUK_TRY: 'Kontakt bruker',
  KONT_BRUK_UFO: 'Kontakt bruker',
  KONT_BRUK_VEN: 'Kontakt bruker',
  KONT_BRUK_YRA: 'Kontakt bruker',
  KONT_BRUK_YRK: 'Kontakt bruker',
  KONTROLLVEDTAK_STO: 'Kontroller vedtak',
  KON_UTG_SCA_DOK_AAP: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_AAR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_AGR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_BAR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_BID: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_BII: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_BIL: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_DAG: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_ENF: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_ERS: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_FEI: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_FOR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_FOS: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_FUL: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_GEN: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_GRA: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_GRU: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_HEL: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_HJE: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_IAR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_IND: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_KLA: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_KOM: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_KON: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_KTR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_MED: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_MOB: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_MOT: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_OKO: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_OMS: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_OPP: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_OVR: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_PEN: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_PER: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_REH: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_REK: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_SAK: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_SER: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_STO: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_SUP: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_SYK: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_SYM: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_TIL: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_TRK: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_TRY: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_UFO: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_VEN: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_YRA: 'Kontroller utgående skannet dokument',
  KON_UTG_SCA_DOK_YRK: 'Kontroller utgående skannet dokument',
  KONY_BAR: 'Konsekvens for ytelse',
  KONY_BIL: 'Konsekvens for ytelse',
  KONY_ENF: 'Konsekvens for ytelse',
  KONY_FOR: 'Konsekvens for ytelse',
  KONY_FOS: 'Konsekvens for ytelse',
  KONY_GRA: 'Konsekvens for ytelse',
  KONY_GRU: 'Konsekvens for ytelse',
  KONY_HJE: 'Konsekvens for ytelse',
  KONY_KON: 'Konsekvens for ytelse',
  KONY_OMS: 'Konsekvens for ytelse',
  KONY_SUP: 'Konsekvens for ytelse',
  KONY_YRK: 'Konsekvens for ytelse',
  KRA_DOD: 'Død',
  KRA: 'Krav',
  LTOKORR_STO: 'LTO/korrigering',
  MAN: 'Manuell behandling',
  MANPOS_STO: 'Manuell postering OS',
  MAN_UTB_BAR: 'Manglende utbetaling',
  MAN_UTB_BIL: 'Manglende utbetaling',
  MAN_UTB_ENF: 'Manglende utbetaling',
  MAN_UTB_ERS: 'Manglende utbetaling',
  MAN_UTB_FOR: 'Manglende utbetaling',
  MAN_UTB_FOS: 'Manglende utbetaling',
  MAN_UTB_GRA: 'Manglende utbetaling',
  MAN_UTB_GRU: 'Manglende utbetaling',
  MAN_UTB_HEL: 'Manglende utbetaling',
  MAN_UTB_HJE: 'Manglende utbetaling',
  MAN_UTB_KON: 'Manglende utbetaling',
  MAN_UTB_OMS: 'Manglende utbetaling',
  MAN_UTB_SAK: 'Manglende utbetaling',
  MAN_UTB_SUP: 'Manglende utbetaling',
  MAN_UTB_YRK: 'Manglende utbetaling',
  MEDL_OVR: '4 - Medlemskap',
  MOTB_BAR: 'Besvare henvendelse',
  MOTB_BIL: 'Besvare henvendelse',
  MOTB_ENF: 'Besvare henvendelse',
  MOTB_FOR: 'Besvare henvendelse',
  MOTB_FOS: 'Besvare henvendelse',
  MOTB_GRA: 'Besvare henvendelse',
  MOTB_GRU: 'Besvare henvendelse',
  MOTB_HJE: 'Besvare henvendelse',
  MOTB_KON: 'Besvare henvendelse',
  MOTB_OMS: 'Besvare henvendelse',
  MOTB_SUP: 'Besvare henvendelse',
  MOTB_YRK: 'Besvare henvendelse',
  MOTK_BAR: 'Krav mottatt',
  MOTK_BIL: 'Krav mottatt',
  MOTK_ENF: 'Krav mottatt',
  MOTK_ERS: 'Krav mottatt',
  MOTK_FOR: 'Krav mottatt',
  MOTK_FOS: 'Krav mottatt',
  MOTK_GRA: 'Krav mottatt',
  MOTK_GRU: 'Krav mottatt',
  MOTK_HEL: 'Krav mottatt',
  MOTK_HJE: 'Krav mottatt',
  MOTK_KON: 'Krav mottatt',
  MOTK_MED: 'Krav mottatt',
  MOTK_OMS: 'Krav mottatt',
  MOTK_SAK: 'Krav mottatt',
  MOTK_SUP: 'Krav mottatt',
  MOTK_TRY: 'Krav mottatt',
  MOTK_YRK: 'Krav mottatt',
  NODUTBET_STO: 'Nødutbetaling',
  OKO_GEN: 'Generell',
  OKO_OS: 'Oppdrag (OS)',
  OKO_REF_KR: 'Refusjonskrav',
  OKO_STOPP: 'Stopp',
  OKO_TBK: 'Tilbakekreving',
  OKO_TREKK: 'Trekk',
  OKO_UR: 'Utbetalingsreskontro (UR)',
  OKO_UTB: 'Utbetaling',
  OPPFOLG_STO: 'Oppfølging',
  OPPINF_OPP: 'Registrer oppfølgningsinfo sykefravær',
  ORI_SAK_BAR: 'Orienter om saksgang',
  ORI_SAK_BIL: 'Orienter om saksgang',
  ORI_SAK_ENF: 'Orienter om saksgang',
  ORI_SAK_ERS: 'Orienter om saksgang',
  ORI_SAK_FOR: 'Orienter om saksgang',
  ORI_SAK_FOS: 'Orienter om saksgang',
  ORI_SAK_GRA: 'Orienter om saksgang',
  ORI_SAK_GRU: 'Orienter om saksgang',
  ORI_SAK_HJE: 'Orienter om saksgang',
  ORI_SAK_KON: 'Orienter om saksgang',
  ORI_SAK_OMS: 'Orienter om saksgang',
  ORI_SAK_SAK: 'Orienter om saksgang',
  ORI_SAK_SUP: 'Orienter om saksgang',
  ORI_SAK_UTB_BAR: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_BIL: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_ENF: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_ERS: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_FOR: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_FOS: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_GRA: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_GRU: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_HEL: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_HJE: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_KON: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_OMS: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_SAK: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_SUP: 'Orienter om saksgang og utbetaling',
  ORI_SAK_UTB_YRK: 'Orienter om saksgang og utbetaling',
  ORI_SAK_YRK: 'Orienter om saksgang',
  ORI_UTB_BAR: 'Orienter om utbetaling',
  ORI_UTB_BIL: 'Orienter om utbetaling',
  ORI_UTB_ENF: 'Orienter om utbetaling',
  ORI_UTB_ERS: 'Orienter om utbetaling',
  ORI_UTB_FOR: 'Orienter om utbetaling',
  ORI_UTB_FOS: 'Orienter om utbetaling',
  ORI_UTB_GRA: 'Orienter om utbetaling',
  ORI_UTB_GRU: 'Orienter om utbetaling',
  ORI_UTB_HJE: 'Orienter om utbetaling',
  ORI_UTB_KON: 'Orienter om utbetaling',
  ORI_UTB_OMS: 'Orienter om utbetaling',
  ORI_UTB_SAK: 'Orienter om utbetaling',
  ORI_UTB_SUP: 'Orienter om utbetaling',
  ORI_UTB_YRK: 'Orienter om utbetaling',
  ORI_VED_BER_BAR: 'Orienter om vedtak og beregning',
  ORI_VED_BER_BIL: 'Orienter om vedtak og beregning',
  ORI_VED_BER_ENF: 'Orienter om vedtak og beregning',
  ORI_VED_BER_ERS: 'Orienter om vedtak og beregning',
  ORI_VED_BER_FOR: 'Orienter om vedtak og beregning',
  ORI_VED_BER_FOS: 'Orienter om vedtak og beregning',
  ORI_VED_BER_GRA: 'Orienter om vedtak og beregning',
  ORI_VED_BER_GRU: 'Orienter om vedtak og beregning',
  ORI_VED_BER_HEL: 'Orienter om vedtak og beregning',
  ORI_VED_BER_HJE: 'Orienter om vedtak og beregning',
  ORI_VED_BER_KON: 'Orienter om vedtak og beregning',
  ORI_VED_BER_MED: 'Orienter om vedtak og beregning',
  ORI_VED_BER_OMS: 'Orienter om vedtak og beregning',
  ORI_VED_BER_SAK: 'Orienter om vedtak og beregning',
  ORI_VED_BER_SUP: 'Orienter om vedtak og beregning',
  ORI_VED_BER_YRK: 'Orienter om vedtak og beregning',
  PRIOR_TREKK_OKO: 'Prioriterte trekk',
  RE_BII: '2 - Regnskap',
  REFUSJON_STO: 'Refusjonskrav',
  REFUSJON_TRK: 'Refusjonskrav',
  REG_HENV_IAR: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_OPA: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_PER: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_REK: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_SAA: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_SYK: 'Registrer henvendelse - arbeidsgiver',
  REG_HENV_TIL: 'Registrer henvendelse - arbeidsgiver',
  REGNSKAP_OKO: 'Regnskap',
  REGNSK_STO: 'Regnskap',
  REGULERING: 'Regulering av pensjon',
  RV_BID: '1 - Revurdering',
  SALDOFLYTT_STO: 'Saldflytt',
  SD_MOT: 'Diverse skanning',
  SETTVENT_STO: 'Sett utbetaling på vent',
  SF_MOT: 'Feilføring person',
  SKATTEKORRIG_STO: 'Skattekorrigering',
  SKATTEKORRIG_TRK: 'Skattekorrigering',
  SO_BID: '1 - Søknad',
  SPM_OG_SVR: 'Besvar spørsmål fra nav.no',
  SR_MOT: 'Retur original',
  STARTV_AAP: 'Start Vedtaksbehandling',
  STARTV_DAG: 'Start vedtaksbehandling',
  STARTV_FEI: 'Start Vedtaksbehandling',
  STARTV_IND: 'Start vedtaksbehandling',
  STARTV_MOB: 'Start vedtaksbehandling',
  STARTV_OPP: 'Start vedtaksbehandling',
  STARTV_YRA: 'Start vedtaksbehandling',
  STOPP_STO: 'Stopp',
  STOPP_TRK: 'Stopp',
  SVAR_IK_MOT_AAP: 'Svar ikke mottatt',
  SVAR_IK_MOT_AGR: 'Svar ikke mottatt',
  SVAR_IK_MOT_BAR: 'Svar ikke mottatt',
  SVAR_IK_MOT_BID: 'Svar ikke mottatt',
  SVAR_IK_MOT_BIL: 'Svar ikke mottatt',
  SVAR_IK_MOT_DAG: 'Svar ikke mottatt',
  SVAR_IK_MOT_ENF: 'Svar ikke mottatt',
  SVAR_IK_MOT_FEI: 'Svar ikke mottatt',
  SVAR_IK_MOT_FOR: 'Svar ikke mottatt',
  SVAR_IK_MOT_FOS: 'Svar ikke mottatt',
  SVAR_IK_MOT_FUL: 'Svar ikke mottatt',
  SVAR_IK_MOT_GEN: 'Svar ikke mottatt',
  SVAR_IK_MOT_GRA: 'Svar ikke mottatt',
  SVAR_IK_MOT_GRU: 'Svar ikke mottatt',
  SVAR_IK_MOT_HEL: 'Svar ikke mottatt',
  SVAR_IK_MOT_HJE: 'Svar ikke mottatt',
  SVAR_IK_MOT_IND: 'Svar ikke mottatt',
  SVAR_IK_MOT_KIR: 'Svar ikke mottatt',
  SVAR_IK_MOT_KOM: 'Svar ikke mottatt',
  SVAR_IK_MOT_KON: 'Svar ikke mottatt',
  SVAR_IK_MOT_MED: 'Svar ikke mottatt',
  SVAR_IK_MOT_MOB: 'Svar ikke mottatt',
  SVAR_IK_MOT_OMS: 'Svar ikke mottatt',
  SVAR_IK_MOT_OPP: 'Svar ikke mottatt',
  SVAR_IK_MOT_PEN: 'Svar ikke mottatt',
  SVAR_IK_MOT_REH: 'Svar ikke mottatt',
  SVAR_IK_MOT_SAK: 'Svar ikke mottatt',
  SVAR_IK_MOT_SAP: 'Svar ikke mottatt',
  SVAR_IK_MOT_SER: 'Svar ikke mottatt',
  SVAR_IK_MOT_SIK: 'Svar ikke mottatt',
  SVAR_IK_MOT_STO: 'Svar ikke mottatt',
  SVAR_IK_MOT_SUP: 'Svar ikke mottatt',
  SVAR_IK_MOT_SYK: 'Svar ikke mottatt',
  SVAR_IK_MOT_SYM: 'Svar ikke mottatt',
  SVAR_IK_MOT_TRK: 'Svar ikke mottatt',
  SVAR_IK_MOT_TRY: 'Svar ikke mottatt',
  SVAR_IK_MOT_UFO: 'Svar ikke mottatt',
  SVAR_IK_MOT_VEN: 'Svar ikke mottatt',
  SVAR_IK_MOT_YRA: 'Svar ikke mottatt',
  SVAR_IK_MOT_YRK: 'Svar ikke mottatt',
  TPS_PEN: 'Personhendelse',
  TREKKFORESPOR_OKO: 'Trekkforespørsel',
  TREKK_STO: 'Trekk',
  TREKK_TRK: 'Trekk',
  TVU_FOR_PEN: 'Tvungen forvaltning',
  TVU_FOR_UFO: 'Tvungen forvaltning',
  UTB_STO: 'Utbetaling',
  UT_JFR_PEN: 'Journalføring utgående',
  UT_JFR_UFO: 'Journalføring utgående',
  VEIINFO_FUL: 'Gi veiledning og informasjon',
  VTR_OKO: 'Vederlagstrekk',
  VUR_AAR: 'Vurder dokument',
  VUR_AGR: 'Vurder dokument',
  VUR_BAR: 'Vurder dokument',
  VUR_BIL: 'Vurder dokument',
  VURD_HENV_AAP: 'Vurder henvendelse',
  VURD_HENV_AAR: 'Vurder henvendelse',
  VURD_HENV_AGR: 'Vurder henvendelse',
  VURD_HENV_BAR: 'Vurder henvendelse',
  VURD_HENV_BID: 'Vurder henvendelse',
  VURD_HENV_BIL: 'Vurder henvendelse',
  VURD_HENV_DAG: 'Vurder henvendelse',
  VURD_HENV_ENF: 'Vurder henvendelse',
  VURD_HENV_ERS: 'Vurder henvendelse',
  VURD_HENV_FEI: 'Vurder henvendelse',
  VURD_HENV_FOR: 'Vurder henvendelse',
  VURD_HENV_FOS: 'Vurder henvendelse',
  VURD_HENV_FUL: 'Vurder henvendelse',
  VURD_HENV_GRA: 'Vurder henvendelse',
  VURD_HENV_GRU: 'Vurder henvendelse',
  VURD_HENV_HEL: 'Vurder henvendelse',
  VURD_HENV_HJE: 'Vurder henvendelse',
  VURD_HENV_IAR: 'Vurder henvendelse',
  VURD_HENV_IND: 'Vurder henvendelse',
  VURD_HENV_KON: 'Vurder henvendelse',
  VURD_HENV_KTR: 'Vurder henvendelse',
  VURD_HENV_MED: 'Vurder henvendelse',
  VURD_HENV_MOB: 'Vurder henvendelse',
  VURD_HENV_OKO: 'Vurder henvendelse',
  VURD_HENV_OMS: 'Vurder henvendelse',
  VURD_HENV_OPA: 'Vurder henvendelse',
  VURD_HENV_OPP: 'Vurder henvendelse',
  VURD_HENV_PEN: 'Vurder henvendelse',
  VURD_HENV_PER: 'Vurder henvendelse',
  VURD_HENV_REH: 'Vurder henvendelse',
  VURD_HENV_REK: 'Vurder henvendelse',
  VURD_HENV_SAA: 'Vurder henvendelse',
  VURD_HENV_SAK: 'Vurder henvendelse',
  VURD_HENV_SAP: 'Vurder henvendelse',
  VURD_HENV_SER: 'Vurder henvendelse',
  VURD_HENV_STO: 'Vurder henvendelse',
  VURD_HENV_SUP: 'Vurder henvendelse',
  VURD_HENV_SYK: 'Vurder henvendelse',
  VURD_HENV_TIL: 'Vurder henvendelse',
  VURD_HENV_TRK: 'Vurder henvendelse',
  VURD_HENV_TRY: 'Vurder henvendelse',
  VURD_HENV_UFO: 'Vurder henvendelse',
  VURD_HENV_YRA: 'Vurder henvendelse',
  VURD_HENV_YRK: 'Vurder henvendelse',
  VUR_ENF: 'Vurder dokument',
  VUR_ERS: 'Vurder dokument',
  VUR_FOR: 'Vurder dokument',
  VUR_FOS: 'Vurder dokument',
  VUR_FUL: 'Vurder dokument',
  VUR_GEN: 'Vurder dokument',
  VUR_GRA: 'Vurder dokument',
  VUR_GRU: 'Vurder dokument',
  VUR_HEL: 'Vurder dokument',
  VUR_HJE: 'Vurder dokument',
  VUR_KONS_YTE_AAP: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_BAR: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_BIL: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_DAG: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_ENF: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_ERS: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_FOR: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_FOS: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_GEN: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_GRA: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_GRU: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_HEL: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_HJE: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_IND: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_KON: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_OMS: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_PEN: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_SAK: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_SUP: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_SYK: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_UFO: 'Vurder konsekvens for ytelse',
  VUR_KONS_YTE_YRK: 'Vurder konsekvens for ytelse',
  VUR_KON: 'Vurder dokument',
  VUR_KTR: 'Vurder dokument',
  VUR_MED: 'Vurder dokument',
  VUR_OMS: 'Vurder dokument',
  VUR_OPA: 'Vurder dokument',
  VUR_REH: 'Vurder dokument',
  VUR_SAA: 'Vurder dokument',
  VUR_SAK: 'Vurder dokument',
  VUR_SER: 'Vurder dokument',
  VUR_STO: 'Vurder dokument',
  VUR_SUP: 'Vurder dokument',
  VUR_SVAR_AAP: 'Vurder svar',
  VUR_SVAR_AGR: 'Vurder svar',
  VUR_SVAR_BAR: 'Vurder svar',
  VUR_SVAR_BID: 'Vurder svar',
  VUR_SVAR_BIL: 'Vurder svar',
  VUR_SVAR_DAG: 'Vurder svar',
  VUR_SVAR_ENF: 'Vurder svar',
  VUR_SVAR_FEI: 'Vurder svar',
  VUR_SVAR_FOR: 'Vurder svar',
  VUR_SVAR_FOS: 'Vurder svar',
  VUR_SVAR_FUL: 'Vurder svar',
  VUR_SVAR_GEN: 'Vurder svar',
  VUR_SVAR_GRA: 'Vurder svar',
  VUR_SVAR_GRU: 'Vurder svar',
  VUR_SVAR_HEL: 'Vurder svar',
  VUR_SVAR_HJE: 'Vurder svar',
  VUR_SVAR_IND: 'Vurder svar',
  VUR_SVAR_KOM: 'Vurder svar',
  VUR_SVAR_KON: 'Vurder svar',
  VUR_SVAR_KTR: 'Vurder svar',
  VUR_SVAR_MED: 'Vurder svar',
  VUR_SVAR_MOB: 'Vurder svar',
  VUR_SVAR_OMS: 'Vurder svar',
  VUR_SVAR_OPP: 'Vurder svar',
  VUR_SVAR_PEN: 'Vurder svar',
  VUR_SVAR_REH: 'Vurder svar',
  VUR_SVAR_SAK: 'Vurder svar',
  VUR_SVAR_SAP: 'Vurder svar',
  VUR_SVAR_SER: 'Vurder svar',
  VUR_SVAR_SIK: 'Vurder svar',
  VUR_SVAR_STO: 'Vurder svar',
  VUR_SVAR_SUP: 'Vurder svar',
  VUR_SVAR_SYK: 'Vurder svar',
  VUR_SVAR_SYM: 'Vurder svar',
  VUR_SVAR_TRK: 'Vurder svar',
  VUR_SVAR_TRY: 'Vurder svar',
  VUR_SVAR_UFO: 'Vurder svar',
  VUR_SVAR_VEN: 'Vurder svar',
  VUR_SVAR_YRA: 'Vurder svar',
  VUR_SVAR_YRK: 'Vurder svar',
  VUR_SYK: 'Vurder dokument',
  VUR_TRK: 'Vurder dokument',
  VUR_TRY: 'Vurder dokument',
  VUR_UFO: 'Vurder dokument',
  VUR_VEN: 'Vurder dokument',
  VUR_YRK: 'Vurder dokument',
}

const OPPGAVE_PRIORITET = {
  HOY: 'Høy',
  NORM: 'Normal',
  LAV: 'Lav',
}

export const decodeOppgaveKode = makeDecoder(OPPGAVE_KODE)
export const decodeOppgavePrioritet = makeDecoder(OPPGAVE_PRIORITET)
