import { makeDecoder } from '~/common/decode'

const UNDERKATEGORI_KODE = {
  AEV_MANG: 'AEV Mangler',
  AFP: 'AFP',
  AFP_OKO: 'AFP',
  AFP_PRIVAT: 'AFP Privat',
  AFP_PRIVAT_OKO: 'AFP Privat',
  AKT_HJE: 'Aktivitetshjelpemidler',
  ALDERSPEN: 'Alderspensjon',
  ALDERSPEN_BUTL: 'Alderspensjon - Bosatt utland',
  ALDERSPEN_NAT: 'Alderspensjon - Nasjonal',
  ALDERSPEN_OKO: 'Alderspensjon',
  ALDERSPEN_UTLT: 'Alderspensjon - Utlandstilsnitt',
  ANSOS_KNA: 'Andre sosiale tjenester',
  ARBD_KNA: 'Arbeid',
  ARBEIDSTILSYNSME_YRK: 'Arbeidstilsynsmelding',
  ATTFORINGSLAN_STO: 'Attføringslån',
  BARNEPEN: 'Barnepensjon',
  BARNEPEN_BUTL: 'Barnepensjon - Bosatt utland',
  BARNEPEN_NAT: 'Barnepensjon - Nasjonal',
  BARNEPEN_OKO: 'Barnepensjon',
  BARNEPEN_UTLT: 'Barnepensjon - Utlandstilsnitt',
  BARNETILSYN_ENF: 'Barnetilsyn',
  BARNETRYGD_STO: 'Barnetrygd',
  BARNS_SYKDOM_STO: 'Barns Sykdom',
  BIDRAG_STO: 'Bidrag',
  BIL_BIL: 'Bil',
  BIL_KNA: 'Bil',
  BIL_STO: 'Bil',
  BILUTSTYR_BIL: 'Bilutstyr',
  DIA_ANG_AEV: 'Dialog ang. AEV',
  DIA_OM_OPPF: 'Dialog om oppfølgingsvedtaket',
  ENGANGSST_FOR: 'Engangsstønad',
  ENS_FORS_OKO: 'Enslig forsørger',
  EOS_BAR: 'EØS',
  ERSTATNING_STO: 'Erstatninger',
  FAMILEPLEIER_ARE: 'Familiepleierpensjon',
  FAMILIEPLEIER: 'Familiepleier',
  FAMILIEPLEIER_OKO: 'Familiepleier',
  FMLI_KNA: 'Familie',
  FORELDREPE_FOR: 'Foreldrepenger',
  FORELDREPE_STO: 'Foreldrepenger',
  FORSIKRING_STO: 'Forsikring',
  FRIVILLIGYR_FOS: 'Frivillig yrkesskadeforsikring',
  GAM_YRK: 'Gammel yrkesskade',
  GAM_YRK_OKO: 'Gammel yrkesskade',
  GJENL_EKTEF_BUTL: 'Gjenlevende ektefelle - Bosatt utland',
  GJENL_EKTEFELLE: 'Gjenlevende ektefelle',
  GJENL_EKTEFELLE_OKO: 'Gjenlevende ektefelle',
  GJENL_EKTEF_NAT: 'Gjenlevende ektefelle - Nasjonal',
  GJENL_EKTEF_UTLT: 'Gjenlevende ektefelle - Utlandstilsnitt',
  GJENLEVENDE_ARE: 'Gjenlevendepensjon',
  GRAVERDSTONAD__STO: 'Gravferdsstønad',
  GRU_HJELP_OKO: 'Grunn-og hjelpestønad',
  GRUNNSTONAD_GRU: 'Grunnstønad',
  HELFO_STO: 'HELFO',
  HJELPEMIDLER_STO: 'Hjelpemidler',
  HJELPESTONAD_GRU: 'Hjelpestønad',
  HJLPM_KNA: 'Hjelpemidler',
  INFORMASJON_BAR: 'Informasjon',
  INFORMASJON_BIL: 'Informasjon',
  INFORMASJON_ENF: 'Informasjon',
  INFORMASJON_FOR: 'Informasjon',
  INFORMASJON_FOS: 'Informasjon',
  INFORMASJON_GRA: 'Informasjon',
  INFORMASJON_GRU: 'Informasjon',
  INFORMASJON_HJE: 'Informasjon',
  INFORMASJON_KON: 'Informasjon',
  INFORMASJON_OMS: 'Informasjon',
  INFORMASJON_SUP: 'Informasjon',
  INFORMASJON_YRK: 'Informasjon',
  INNT: 'INNT',
  KJOREOPPLARING_BIL: 'Kjøreopplæring',
  KONTANTSTOTTE_STO: 'Kontantstøtte',
  KRIGSPEN: 'Krigspensjon',
  KRIGSPEN_OKO: 'Krigspensjon',
  MENERSTATNING_YRK: 'Menerstatning',
  OKSOS_KNA: 'Økonomisk sosialhjelp',
  OK_YTELSE_OKO: 'Oslo kommune ytelse',
  OMSORGSPE_OMS: 'Omsorgspenger',
  OMSORGSPOENG: 'Omsorgspoeng',
  OPPF_VEDTAK_MANG: 'Oppfølgingsvedtak mangler',
  OPPLARINGSPE_OMS: 'Opplæringspenger',
  ORDINAR_BAR: 'Ordinær',
  ORT_HJE_KNA: 'Ortopediske hjelpemidler',
  OVERGANGST_ENF: 'Overgangsstønad',
  OVRG_KNA: 'Øvrig',
  PEN: 'PEN',
  PENPOST: 'PENPOST',
  PENS_KNA: 'Pensjon',
  PLEIEPENGERIN_OMS: 'Pleiepenger institusjon',
  PLEIEPENGERPA_OMS: 'Pleiepenger pårørende',
  PLEIEPENGERSY_OMS: 'Pleiepenger sykt barn',
  PTS_YTELSE_OKO: 'Pensjonstrygd sjømenn',
  SAKSOMKOSTNINGER_STO: 'Saksomkostninger',
  SAMMUTB: 'SAMMUTB',
  SELVSTENDIGNA_FOS: 'Selvstendig næringsdrivende',
  SKADEMELDING_YRK: 'Skademelding',
  SMAABED_FOS: 'Små bedrifter',
  SPK_YTELSE_OKO: 'SPK ytelse',
  SUPPL_STONAD_STO: 'Supplerende stønad',
  SVANGERSKAPSPE_FOR: 'Svangerskapspenger',
  SYKEPENGER__STO: 'Sykepenger',
  TBBT: 'TBBT',
  TB: 'TB',
  TIDSBEG_UFORE_STO: 'Tidsbegrenset uførestønad',
  TID_UFS_UFO: 'Tidsbegrenset uførestønad',
  TILSKUDDFL_ENF: 'Tilskudd Flytting',
  UFOREPEN_BUTL: 'Uføretrygd - Bosatt utland',
  UFOREPEN_NAT: 'Uføretrygd - Nasjonal',
  UFOREPEN_OKO: 'Uføretrygd',
  UFOREPEN: 'Uføretrygd',
  UFOREPEN_UTLT: 'Uføretrygd - Utlandstilsnitt',
  UFOREP_UFO: 'Uføretrygd',
  UFRT_KNA: 'Uføretrygd',
  URKLUTB: 'URKLUTB',
  UTBETALING_BAR: 'Utbetaling',
  UTBETALING_BIL: 'Utbetaling',
  UTBETALING_ENF: 'Utbetaling',
  UTBETALING_FOR: 'Utbetaling',
  UTBETALING_FOS: 'Utbetaling',
  UTBETALING_GRA: 'Utbetaling',
  UTBETALING_GRU: 'Utbetaling',
  UTBETALING_KON: 'Utbetaling',
  UTBETALING_OMS: 'Utbetaling',
  UTBETALING_SUP: 'Utbetaling',
  UTBETALING_YRK: 'Utbetaling',
  UTDANNINGSST_ENF: 'Utdanningstønad',
  UTPOST: 'UTPOST',
  UTVIDET_BAR: 'Utvidet',
  VEDTAK_BAR: 'Vedtak',
  VEDTAK_BIL: 'Vedtak',
  VEDTAK_ENF: 'Vedtak',
  VEDTAK_FOR: 'Vedtak',
  VEDTAK_FOS: 'Vedtak',
  VEDTAK_GRA: 'Vedtak',
  VEDTAK_GRU: 'Vedtak',
  VEDTAK_HJE: 'Vedtak',
  VEDTAK_KON: 'Vedtak',
  VEDTAK_OMS: 'Vedtak',
  VEDTAK_SUP: 'Vedtak',
  VEDTAK_YRK: 'Vedtak',
  YRKESSKADE_STO: 'Yrkesskade',
  YRK_OKO: 'Yrkesskade',
}

export const decodeUnderkategoriKode = makeDecoder(UNDERKATEGORI_KODE)
