apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ app.name }}
  namespace: {{ app.namespace }}
  labels:
    team: {{ app.team }}
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: '/internal/live'
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: '/internal/live'
    initialDelay: 3
    timeout: 1
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
  ingresses:
    {{#each app.ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    - name: ALDE_LINK_ENABLED
      value: "{{ alde.link_enabled }}"
    - name: ALDE_BEHANDLING_URL_TEMPLATE
      value: "{{ alde.behandling_url_template }}"
    - name: ENV
      value: {{ app.env }}
    - name: LOKI_API_BASE_URL
      value: "https://{{ loki.apiHost }}"
    - name: PEN_APPLICATION
      value: {{ pen.application }}
    - name: PEN_SCOPE
      value: {{ pen.scope }}
    - name: PEN_SERVICE_NAME
      value: {{ pen.serviceName }}
    - name: PEN_URL
      value: {{ pen.url }}
    - name: PSAK_SAK_URL_TEMPLATE
      value: "{{ psak.sak_url_template }}"
  accessPolicy:
    outbound:
      external:
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
        - host: {{ pen.outbound }}
        - host: {{ loki.apiHost }}
  azure:
    application:
      tenant: {{ azure.tenant }}
      enabled: true
      claims:
        groups:
          - id: {{ azure.grupper.drift }}
          - id: {{ azure.grupper.verdande-les }}
          - id: {{ azure.grupper.verdande-skriv }}
          - id: {{ azure.grupper.verdande-admin }}
        extra:
          - NAVident
      replyURLs:
        - "http://localhost:3000/auth/callback"
        - "http://localhost:3000/api/auth/callback/azure-ad"
        {{#each app.ingresses as |url|}}
        - "{{url}}/auth/callback"
        {{/each}}
    sidecar:
      enabled: true
      autoLogin: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
