name: Build and Publish Storybook to GitHub Pages
on:
  push:
    branches:
      - 'main'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Sett opp og installer frontend avhengigheter
        uses: ./.github/actions/setup-frontend

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: 'storybook-static'
          overwrite: true

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          token: ${{ github.token }}
